### ISSUE TITLE
Board link doesn't work

### ISSUE THREAD

**Issue by ahrasis** [interlab/elk-flarum-style#3]
Redirect is working now but board link doesn't work anymore (version 0.2.2).

**Comment by interlab** [comment]
Thanks. 
Hmmm ... I have no errors (or I did not notice).
Your browser name?
Your browser version?
Click F12  -> Console -> see errors and report here

**Comment by interlab** [comment]
I made the correction, try a new version

**Comment by interlab** [comment]
error still exists?

**Comment by ahrasis** [comment]
Sorry, I think, last time I checked after the update, there is no error. But I haven't checked it for quite some times.
