### ISSUE TITLE
Not working on EA 1.1.1

### ISSUE THREAD

**Issue by ahrasis** [interlab/elk-flarum-style#8]
I can't get it working on EA 1.1.1 using the latest version 0.5.0. It seems no error but could be of multi tenancy addon. I'll check again.

**Comment by interlab** [comment]
maybe this:
> How to Use in ElkArte 1.1:
Home -> Administration Center -> Features and Options -> Layout
Select the action to show on the front page: Flarumstyle addon

**Comment by ahrasis** [comment]
Ok. That works. I'll close this.
